version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.6.0

    steps:
      - checkout

      - run:
          name: "simple echo"
          command: echo ${CIRCLE_PROJECT_USERNAME}

      - run:
          name: "Set Org Name"
          command: echo 'export orgName=${CIRCLE_PROJECT_USERNAME}' > $BASH_EN

      - run:
          name: "simple echo"
          command: echo $orgName

      - run:
          name: Yarn Install
          command: yarn install

      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "praveenn-vbi@users.noreply.github.com"
            git config --global user.name "praveenn-vbi"
            echo "machine github.com login praveenn-vbi password $GITHUB_TOKEN" > ~/.netrc
            GIT_USER=praveenn-vbi yarn deploy
